### ISSUE TITLE
Reinstate the plugin to work with WordPress 6.7 and/or the latest version of Gutenberg

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/sb-field-block#6]
After spending some time looking at block bindings for oik-events, I once again considered how to implement a block to display oik's fields such as post meta and virtual fields.
It took me some time to realise I'd already attempted to solve the problem back in 2021.

But it's not working. The `oiksb/sb-field-block` server side code works. But the front end doesn't work.  

```
Uncaught TypeError: Cannot read properties of undefined (reading 'mark')
    at ../../../../wordpress/wp-content/plugins/sb-field-block/src/store.js (store.js:28:19)
    at __webpack_require__ (bootstrap:79:1)
    at ../../../../wordpress/wp-content/plugins/sb-field-block/src/edit.js (index.js?ver=5c526f0441de9462b5b163955cc70335:468:65)
    at __webpack_require__ (bootstrap:79:1)
    at ../../../../wordpress/wp-content/plugins/sb-field-block/src/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:79:1)
    at checkDeferredModules (bootstrap:45:1)
    at bootstrap:152:1
    at bootstrap:152:1
```

**Comment by bobbingwide** [comment]
In order to get the block to work I needed to upgrade wp-scripts from v14.0.1 to v30.4.0
This included making similar changes to those documented for other plugins.

- Update wp-scripts using `npm run packages-update`... if it works
- Otherwise remove node_nodules and install 
- Update `package.json` as required
- Move the `src` files for the block into a subdirectory
- Add `webpack.config.js`
- Change `block.json` to deliver different files in the build folder 
- Consider script translations.

See also https://github.com/bobbingwide/oik/issues/202

**Comment by bobbingwide** [comment]
The next problem was that, for the `event` post type fields of type `text` weren't being populated in the editor.
They were being displayed with the message "Please set Field name".
This was because the `event` CPT did not support `custom-fields`. 
Once I'd changed this the fields in the metabox ended up getting default values.
This was due to the default value being set in `oik_events_register_post_meta()`'s call to `register_post_meta()`

**Comment by bobbingwide** [comment]
I get some messages when building the Javascript. Should I be worried?

```
LOG from ./node_modules/sass-loader/dist/cjs.js sass-loader ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[3].use[3]!./src/sb-field-block/editor.scss
<w> Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
<w>
<w> More info: https://sass-lang.com/d/legacy-js-api
<w>
<w> null
```

**Comment by bobbingwide** [comment]
In v0.0.1 I'd managed to get the plugin to work and had started developing fields and virtual fields to be displayed by the oik-events plugin.
